language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive texlive-latex-extra texlive-pictures texlive-lang-spanish
script:
  - grunt
